#!/usr/bin/env python

from subprocess import run
from setup import Setup
from ui import input_bool
from sys import argv

if len(argv) < 2:
    print('archerry <file>')
    exit()

Setup.from_input(argv[1]).write_dist('dist')
if input_bool('Run'):
    run('bash dist/main.bash | tee archerry.log', shell=True)
    run(['mv', '-v', 'archerry.log', '/mnt/var/log'])
